#Pacman
alias update="sudo pacman -Syu"
alias upall="pacaur -Syu --noconfirm"
alias p="pacman"
alias pQ="pacman -Q"
alias pqs="pacman -Qs"
alias pqi="pacman -Qi"
alias pS="sudo pacman -S"
alias psi="pacman -Si"
alias pR="sudo pacman -R"
alias prc="sudo pacman -Rc"
alias prs="sudo pacman -Rs"
alias prsc="sudo pacman -Rsc"
alias pA="sudo pacman -A"
alias pU="sudo pacman -U"
alias pO="sudo pacman-optimize"