#!/bin/python
# -*- coding: utf-8 -*-

import requests

CITY = "1279233"
API_KEY = "0dbbf8ec41e50f148b22ac8ccb187c3a"
UNITS = "Metric"
UNIT_KEY = "C"

REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}&units={}".format(CITY,API_KEY, UNITS))
try:
    # HTTP CODE = OK
    if REQ.status_code == 200:
        CURRENT = REQ.json()["weather"][0]["description"].capitalize()
        # TRANSLATE TO FRENCH
        if CURRENT == "Clear sky":
            CURRENT = "Clear sky"
        elif CURRENT == "Few clouds":
            CURRENT = "Few Clouds"
        elif CURRENT == "Mist":
            CURRENT = "Mist"
        elif CURRENT == "Light rain":
            CURRENT = "Light Rain"
        elif CURRENT == "Moderate rain":
            CURRENT = "Moderate Rain"
        elif CURRENT == "Haze":
            CURRENT = "Haze"
        elif CURRENT == "Broken clouds":
            CURRENT = "Broken Clouds"
        elif CURRENT == "Snow":
            CURRENT = "Snow"
        elif CURRENT == "Light snow":
            CURRENT = "Light Snow"
        elif CURRENT == "Light rain and snow":
            CURRENT = "Light Rain and Snow"
        else:
            CURRENT = CURRENT

        TEMP = int(float(REQ.json()["main"]["temp"]))
        print("{}, {} °{}".format(CURRENT, TEMP, UNIT_KEY))
    else:
        print("Error: BAD HTTP STATUS CODE " + str(REQ.status_code))
except (ValueError, IOError):
    print("Error: Unable print the data")
