#!/bin/bash

## Start apps on X

# system apps
bash /home/codin/.screenlayout/triple-monitor-setup.sh &
#bash /home/codin/scripts/live_wallpaper &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pasystray &
udiskie &
#syndaemon -i 1 -K -R &
dunst -config ~/.config/dunst/dunstrc &
#blueman-applet &
nm-applet &
#dropbox &
picom --experimental-backends --backend glx  --config /home/codin/dotfiles/i3_workstation/i3/picom.conf &
# my apps
#slack &
#skypeforlinux &
redshift-gtk &
xfce4-clipman &
#unclutter -root -visible &
#gnome-keyring-daemon -r -d
#hexchat
#transmission-gtk
#opera
#obs
#ptxconf
#thunar
#spotify
#virt-manager
#filezilla
#nautilus
#ptxconf
#xbacklight -set 65
#feh --bg-fill ~/Pictures &
#batterymon &
#xfce4-power-manager &
#psensor &

