#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources


#sudo xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
#sudo xrandr --addmode VGA1 1920x1080

#[ -f ~/.xprofile ] && source ~/.xprofile
#[ -f ~/.bash_profile ] && source ~/.bash_profile
#systemctl --user import-environment DISPLAY

# Ensure that the D-Bus Communication System is running properly to fix         
# File management, authentication, and other essential system processes

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#export SSH_AUTH_SOCK

## Ensure that GTK themes are applied uniformly in the Desktop Environment      
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"


#[ -f ~/.xprofile ] && source ~/.xprofile                                        
#[ -f ~/.bash_profile ] && source ~/.bash_profile   


#exec awesome
#exec startkde
#exec startxfce4
#exec awesome-kde-session
#exec gnome-session
#exec cinnamon-session
#export XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
#export GNOME_SHELL_SESSION_MODE=classic
#exec gnome-session
#XDG_CURRENT_DESKTOP=XFCE4 DESKTOP_SESSION=xfce4
#exec gnome-session
#exec startxfce4
exec i3

