#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources


#sudo xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
#sudo xrandr --addmode VGA1 1920x1080

[ -f ~/.xprofile ] && source ~/.xprofile
[ -f ~/.bash_profile ] && source ~/.bash_profile
#systemctl --user import-environment DISPLAY

#exec awesome
#exec startkde
#exec startxfce4
#exec awesome-kde-session
#exec gnome-session
#exec cinnamon-session
#export XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
#export GNOME_SHELL_SESSION_MODE=classic
#exec gnome-session
#XDG_CURRENT_DESKTOP=XFCE4 DESKTOP_SESSION=xfce4
#exec gnome-session
#exec startxfce4
exec i3

